# Generated by Django 4.2.4 on 2023-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.URLField(unique=True)),
                ("accepted", models.BooleanField(default=True)),
                ("raw_json", models.JSONField()),
                ("preferred_username", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("inbox_url", models.URLField()),
                ("outbox_url", models.URLField()),
            ],
        ),
    ]
