# Generated by Django 4.2.4 on 2023-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitypub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follower",
            options={
                "ordering": ["id"],
                "verbose_name": "Follower",
                "verbose_name_plural": "Followers",
            },
        ),
        migrations.AlterField(
            model_name="follower",
            name="id",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Follower ID",
            ),
        ),
        migrations.AlterModelTable(
            name="follower",
            table="activitypub_followers",
        ),
    ]
