# Generated by Django 5.0.1 on 2024-01-29 14:23

import mentions.models.mixins.mentionable
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "allow_outgoing_webmentions",
                    models.BooleanField(
                        default=mentions.models.mixins.mentionable._outgoing_default,
                        verbose_name="allow outgoing webmentions",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Post ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created"),
                ),
                (
                    "reaction_type",
                    models.IntegerField(
                        choices=[(0, "Like"), (1, "Reply"), (2, "Repost")],
                        default=0,
                        verbose_name="Reaction type",
                    ),
                ),
                (
                    "react_to_url",
                    models.CharField(max_length=1024, verbose_name="Reacting to URL"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
