# Generated by Django 5.0.1 on 2024-01-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reaction",
            options={
                "ordering": ["-create_date"],
                "verbose_name": "Reaction",
                "verbose_name_plural": "Reactions",
            },
        ),
    ]
