# Generated by Django 5.0.2 on 2024-03-02 09:23

import mentions.models.mixins.mentionable
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "allow_outgoing_webmentions",
                    models.BooleanField(
                        default=mentions.models.mixins.mentionable._outgoing_default,
                        verbose_name="allow outgoing webmentions",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Content ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("post", "Post"),
                            ("photo", "Photo"),
                            ("page", "Page"),
                            ("like", "Like"),
                            ("reply", "Reply"),
                            ("repost", "Repost"),
                            ("activity", "Activity"),
                        ],
                        max_length=50,
                        verbose_name="Content type",
                    ),
                ),
                (
                    "content_path",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Content path",
                    ),
                ),
                (
                    "content_meta",
                    models.JSONField(default=dict, verbose_name="Content meta"),
                ),
                (
                    "content_federate",
                    models.BooleanField(default=True, verbose_name="Federate"),
                ),
                (
                    "content_rss_only",
                    models.BooleanField(default=False, verbose_name="RSS only"),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Create date"
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publish date"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Update date"
                    ),
                ),
                (
                    "ranking",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="Search rank"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "cp_content",
                "ordering": ["-create_date"],
            },
        ),
    ]
