# Generated by Django 4.2.4 on 2023-08-28 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Post ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Updated"),
                ),
                (
                    "slug",
                    models.CharField(
                        editable=False, max_length=32, verbose_name="Slug"
                    ),
                ),
                (
                    "post_type",
                    models.IntegerField(
                        choices=[(0, "Note"), (1, "Post")],
                        default=0,
                        verbose_name="Post type",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Published")],
                        default=0,
                        verbose_name="Post status",
                    ),
                ),
                (
                    "rss_only",
                    models.BooleanField(default=False, verbose_name="RSS only"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Title"
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("html", models.TextField(blank=True, null=True, verbose_name="HTML")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "cp_posts",
                "ordering": ["-create_date"],
            },
        ),
    ]
