# Generated by Django 4.2.4 on 2023-08-28 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("text", models.TextField(verbose_name="Markdown text")),
                ("html", models.TextField(blank=True, null=True)),
                (
                    "update_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated"
                    ),
                ),
                (
                    "full_path",
                    models.CharField(
                        editable=False, max_length=525, verbose_name="Full path"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.page",
                        verbose_name="Parent page",
                    ),
                ),
            ],
        ),
    ]
