# Generated by Django 4.2.4 on 2023-08-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["title"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AlterModelTable(
            name="page",
            table="cp_pages",
        ),
    ]
