# Generated by Django 4.2.4 on 2023-09-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_page_ranking_post_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=32, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")],
                default=1,
                verbose_name="Post status",
            ),
        ),
    ]
