# Generated by Django 4.2.4 on 2023-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_alter_post_slug_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/", verbose_name="Photo"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="photo_alt_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt text"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="photo_meta",
            field=models.JSONField(blank=True, null=True, verbose_name="EXIF data"),
        ),
    ]
