# Generated by Django 4.2.4 on 2023-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_post_photo_post_photo_alt_text_post_photo_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo_meta",
            field=models.TextField(blank=True, null=True, verbose_name="EXIF data"),
        ),
    ]
