# Generated by Django 4.2.4 on 2023-10-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_post_photo_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="show_in_nav",
            field=models.BooleanField(default=False, verbose_name="RSS only"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.IntegerField(
                choices=[(0, "Note"), (1, "Post"), (2, "Photo")],
                default=0,
                verbose_name="Post type",
            ),
        ),
    ]
