# Generated by Django 4.2.4 on 2023-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_page_show_in_nav_alter_post_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="show_in_nav",
            field=models.BooleanField(default=False, verbose_name="Show in nav"),
        ),
    ]
