# Generated by Django 4.2.4 on 2023-10-16 11:34

from django.db import migrations, models
import mentions.models.mixins.mentionable


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_alter_page_show_in_nav"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_outgoing_webmentions",
            field=models.BooleanField(
                default=mentions.models.mixins.mentionable._outgoing_default,
                verbose_name="allow outgoing webmentions",
            ),
        ),
    ]
